AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ENV:
    Description: Enter the ENV parameter to describe environment of stack
    ConstraintDescription: must specify dev, hmg or prd.
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - hmg
      - prd 
Resources:
  RoleLambda:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  FuncaoLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub ${ENV}-deploy-aws-calculadora
        S3Key: package.zip
      Environment:
        Variables:
          ENVIRONMENT: !Ref ENV
      Description: lambda function
      FunctionName: !Sub ${ENV}-lambda-calculadora
      Handler: index.handler
      MemorySize: 256
      Role: !GetAtt RoleLambda.Arn
      Runtime: nodejs12.x
      Timeout: 60
Outputs:
  FuncaoLambda:
    Value: !Ref FuncaoLambda
  FuncaoLambdaArn:
    Value: !GetAtt FuncaoLambda.Arn