AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ENV:
    Description: Enter the ENV parameter to describe environment of stack
    ConstraintDescription: must specify dev, hmg or prd.
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - hmg
      - prd 
Resources:
  MeuBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ENV}-deploy-aws-calculadora
Outputs:
  BucketArn:
    Value: !GetAtt [MeuBucket, Arn]
  BucketWebsiteURL:
    Value: !GetAtt [MeuBucket, WebsiteURL]